name: futurstore
description: "Futur Store Decentralized App store"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  austerity: ^1.2.0
  bip39: ^1.0.6
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  cloud_firestore_odm: ^1.0.0-dev.83
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  dart_utils:
    git: https://github.com/bienvenuelisis/dart_utils.git
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  polkadart: ^0.3.2
  polkadart_cli: ^0.3.2
  polkadart_keyring: ^0.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  cloud_firestore_odm_generator: ^1.0.0-dev.83
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # Flutter Localization : https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
  generate: true

polkadart:
  output_dir: lib/generated
  chains:
    relai_network: wss://rpc1.relai.network