name: futurstore
description: "Futur Store Decentralized App store"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.3+9

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  austerity: ^1.2.0
  background_downloader: ^8.2.1
  bip39: ^1.0.6
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  cloud_firestore_odm: ^1.0.0-dev.83
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  dart_utils:
    git: https://github.com/bienvenuelisis/dart_utils.git
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  installed_apps: ^1.5.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  local_storage:
    path: packages/local_storage
  polkadart: ^0.3.2
  polkadart_cli: ^0.3.2
  polkadart_keyring: ^0.3.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  cloud_firestore_odm_generator: ^1.0.0-dev.83
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  # Flutter Localization : https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
  generate: true

polkadart:
  output_dir: lib/generated
  chains:
    relai_network: wss://rpc1.relai.network