name: futurstore
description: "Futur Store Decentralized App store"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bip39: ^1.0.6
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.24.2
  polkadart_cli: ^0.3.2
  polkadart: ^0.3.2
  polkadart_keyring: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
polkadart:
  output_dir: lib/generated
  chains:
    relai_network: wss://rpc1.relai.network